server:
  port: 8090

eureka:
  client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: /gateway
  routes:
    test:
      path: /redirect/**
      url: http://google.com
    account-service:
      path: /account-service/**
      serviceId: account-service
    feign-client:
      path: /feign-client/**
      serviceId: feign-client
